### ISSUE TITLE
Ease recording tubes and walls into building groups

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Helper#11]
Would it be beneficial to add a helper method that mirrors CreateTubeOrWallLine, but instead records it for future building by an AI player? I use it in my mission coding.
`
```C++
// ALREADY EXISTS
void CreateTubeOrWallLine(int x1, int y1, int x2, int y2, map_id type);

// NEW FUNCTION
void RecordTubeOrWallLine(BuildingGroup &buildingGroup, int x1, int y1, int x2, int y2, map_id type)
```

If I were to do this greenfield, I think I would target the following:

```C++
void CreateTubeLine(LOCATION location1, LOCATION location2);
void CreateWallLine(LOCATION location1, LOCATION location2, map_id wallType);

void RecordTubeLine(BuildingGroup& buildingGroup, LOCATION location1, LOCATION location2);
void RecordWallLine(BuildingGroup& buildingGroup, LOCATION location1, LOCATION location2, map_id wallType);
```

But then it wouldn't match the existing function.

**Comment by DanRStevens** [comment]
I like the record idea. We should add that.

----

I admit I'm not in love with the old name. The "Or" never felt right. I'd like to see some improvement there.

In terms of implementation, I can kind of see the `CreateTubeLine` method calling the same implementation as `CreateWallLine`. It would seem like a shame if the code got duplicated. This makes me wonder if there is perhaps a more generic name we can use. Maybe something along the lines of `CreateEarthworkerItem`? I don't much like "Item", though that's probably better than "Or". I think I might also prefer that to duplicating code.

Edit: I was just thinking, if we were going to split the Tube method from the Wall method, it would make more sense if we also split all the Wall methods from each other as well. Then it would be `CreateTubeLine`, `CreateWallLine`, `CreateMicrobeWallLine`, `CreateLavaWallLine`. Not sure if you want to take things that far. Internally, they might all defer to the old `CreateTubeOrWallLine` method.

----

Do we want to consider generalizing this to other structures? Maybe have a way to lay down a line of guard posts? Or residences? Both may require a bit of spacing. The guard posts would also require specifying the turret type separately. That might be a separate issue though.

**Comment by Brett208** [comment]
I'd like to not approach lines of other structures yet. In particular, a line of guard posts might be useful. Otherwise, not so sure.

It sounds like you don't have any issue with breaking changes here to OP2Helper's public interface, so I'll put something together in a branch. I think it has been discussed enough at the interface level.

Thanks,
Brett

**Comment by DanRStevens** [comment]
I think we need to allow for some occasional breakage in the interests of moving forward. Renaming old badly named methods seems worthwhile. It's also reasonably safe to do here, since this is a source code breakage, not a breakage of existing binary code.
