### ISSUE TITLE
Provide enum for Bay index

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Helper#19]
Should we provide an enumeration for bay index values, much like how there is an enumeration for the `PlayerNum`? That would allow easier to read code such as:
```cpp
	truck.PutInGarage(Bay0, garage.Location().x, garage.Location().y);
```

I believe that would be much more self documenting than the current:
```cpp
	truck.PutInGarage(0, garage.Location().x, garage.Location().y);
```

----

One restriction is that we can not change the actual parameter type due to name mangling and linking reasons. We can however simply provide the enum and allow new code to use it. That also has the benefit of not breaking old code.

**Comment by Brett208** [comment]
I think this is a good idea.
