### ISSUE TITLE
Handling BaseBuilderV2

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Helper#8]
BaseBuilderV2 is an uncompleted feature within OP2Helper. I think it has stalled out over time and doesn't seem to have a lot of interest in completing. 

If it is possible, I'd like to consider moving BaseBuilder out of master and into a branch. Since it isn't considered usable/complete yet, it would be better not to be part of the master branch I think. 

I guess if it is definitely dead, we could just delete it as well.

**Comment by DanRStevens** [comment]
Yes. Either.

Actually, maybe just delete it. It'll still be part of history. If we feel like working on it, it can be resurrected in a branch and completed there.
